version: '3'

include:
  - path: ./backend/docker-compose.yml

services:
  web:
    build: ./frontend
    environment:
      NODE_ENV: production
      VITE_API_URL: http://localhost:8000
    ports:
      - "5137:5137"
    depends_on:
      - laravel.test

networks:
  sail:
    driver: bridge