version: '3'
services:
  web:
    build: ./frontend
    environment:
      NODE_ENV: production
      VITE_API_URL: http://backend:8000
    ports:
      - "5137:5137"
  backend:
    build: ./backend
    ports:
      - "8000:8000"
